# Generated by Django 6.0.5 on 2026-05-26 14:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Etudiant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Ce champ ne peut contenir que des lettres et des espaces.",
                                regex="^[A-Za-zÀ-ÖØ-öø-ÿ ]+$",
                            )
                        ],
                    ),
                ),
                (
                    "prenom",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Ce champ ne peut contenir que des lettres et des espaces.",
                                regex="^[A-Za-zÀ-ÖØ-öø-ÿ ]+$",
                            )
                        ],
                    ),
                ),
                ("CIN", models.CharField(max_length=10, unique=True)),
                ("CNE", models.CharField(max_length=20, unique=True)),
                ("date_naissance", models.DateField()),
                (
                    "filiere",
                    models.CharField(
                        choices=[
                            ("API", "API"),
                            ("GI", "GI"),
                            ("GE", "GE"),
                            ("IID", "IID"),
                            ("IRIC", "IRIC"),
                            ("MGSI", "MGSI"),
                            ("GPEE", "GPEE"),
                            ("MASTER", "MASTER"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("API1", "API1"),
                            ("API2", "API2"),
                            ("GI1", "GI1"),
                            ("GI2", "GI2"),
                            ("GI3", "GI3"),
                            ("GE1", "GE1"),
                            ("GE2", "GE2"),
                            ("GE3", "GE3"),
                            ("IID1", "IID1"),
                            ("IID2", "IID2"),
                            ("IID3", "IID3"),
                            ("MGSI1", "MGSI1"),
                            ("MGSI2", "MGSI2"),
                            ("IRIC1", "IRIC1"),
                            ("IRIC2", "IRIC2"),
                            ("IRIC3", "IRIC3"),
                            ("GPEE1", "GPEE1"),
                            ("GPEE2", "GPEE2"),
                            ("GPEE3", "GPEE3"),
                            ("M1", "M1"),
                            ("M2", "M2"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "sexe",
                    models.CharField(choices=[("M", "M"), ("F", "F")], max_length=1),
                ),
                (
                    "telephone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Numéro de téléphone invalide",
                                regex="^(\\\\+212[ ]?[67]\\d{8}|\\\\+33[ ]?6\\d{8}|0[67]\\d{8})$",
                            )
                        ],
                    ),
                ),
                (
                    "ville",
                    models.CharField(
                        choices=[
                            ("Agadir", "Agadir"),
                            ("Aïn Harrouda", "Aïn Harrouda"),
                            ("Al Hoceima", "Al Hoceima"),
                            ("Aït Melloul", "Aït Melloul"),
                            ("Asilah", "Asilah"),
                            ("Azrou", "Azrou"),
                            ("Beni Mellal", "Beni Mellal"),
                            ("Berrechid", "Berrechid"),
                            ("Benslimane", "Benslimane"),
                            ("Berkane", "Berkane"),
                            ("Boujdour", "Boujdour"),
                            ("Casablanca", "Casablanca"),
                            ("Chefchaouen", "Chefchaouen"),
                            ("Dakhla", "Dakhla"),
                            ("Dar Bouazza", "Dar Bouazza"),
                            ("El Jadida", "El Jadida"),
                            ("Errichidia", "Errachidia"),
                            ("Essaouira", "Essaouira"),
                            ("Fès", "Fès"),
                            ("Guercif", "Guercif"),
                            ("Guelmim", "Guelmim"),
                            ("Ifrane", "Ifrane"),
                            ("Kenitra", "Kénitra"),
                            ("Khouribga", "Khouribga"),
                            ("Khemisset", "Khemisset"),
                            ("Khenifra", "Khenifra"),
                            ("Ksar El Kebir", "Ksar El Kebir"),
                            ("Laâyoune", "Laâyoune"),
                            ("Larache", "Larache"),
                            ("Marrakech", "Marrakech"),
                            ("Martil", "Martil"),
                            ("Meknès", "Meknès"),
                            ("Mohammedia", "Mohammedia"),
                            ("Nador", "Nador"),
                            ("Ouarzazate", "Ouarzazate"),
                            ("Oujda", "Oujda"),
                            ("Rabat", "Rabat"),
                            ("Salé", "Salé"),
                            ("Safi", "Safi"),
                            ("Settat", "Settat"),
                            ("Sidi Slimane", "Sidi Slimane"),
                            ("Sidi Kacem", "Sidi Kacem"),
                            ("Tanger", "Tanger"),
                            ("Taza", "Taza"),
                            ("Temara", "Témara"),
                            ("Tétouan", "Tétouan"),
                            ("Tiznit", "Tiznit"),
                            ("Youssoufia", "Youssoufia"),
                            ("Tan-Tan", "Tan-Tan"),
                            ("Souk El Arbaa", "Souk El Arbaa"),
                            ("Oued Zem", "Oued Zem"),
                            ("Taourirt", "Taourirt"),
                            ("Oulad Teima", "Oulad Teima"),
                            ("Fquih Ben Salah", "Fquih Ben Salah"),
                            ("Skhirat", "Skhirat"),
                            ("Midelt", "Midelt"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medecin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Ce champ ne peut contenir que des lettres et des espaces.",
                                regex="^[A-Za-zÀ-ÖØ-öø-ÿ ]+$",
                            )
                        ],
                    ),
                ),
                (
                    "prenom",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Ce champ ne peut contenir que des lettres et des espaces.",
                                regex="^[A-Za-zÀ-ÖØ-öø-ÿ ]+$",
                            )
                        ],
                    ),
                ),
                (
                    "specialite",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Ce champ ne peut contenir que des lettres et des espaces.",
                                regex="^[A-Za-zÀ-ÖØ-öø-ÿ ]+$",
                            )
                        ],
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Numéro de téléphone invalide",
                                regex="^(\\\\+212[ ]?[67]\\d{8}|\\\\+33[ ]?6\\d{8}|0[67]\\d{8})$",
                            )
                        ],
                    ),
                ),
                (
                    "rdv_jr",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "salaire",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Salaire (DH)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medicament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_medicament", models.CharField(max_length=100)),
                (
                    "forme",
                    models.CharField(
                        choices=[
                            ("Comprimé", "Comprimé"),
                            ("Gélule", "Gélule"),
                            ("Solution", "Solution"),
                            ("Sirop", "Sirop"),
                            ("Suspension", "Suspension"),
                            ("Capsule", "Capsule"),
                            ("Injection", "Injection"),
                            ("Gel", "Gel"),
                            ("Crème", "Crème"),
                            ("Pommade", "Pommade"),
                            ("Suppositoire", "Suppositoire"),
                            ("Patch", "Patch"),
                            ("Spray", "Spray"),
                            ("Émulsion", "Émulsion"),
                            ("Poudre", "Poudre"),
                        ],
                        default="comprime",
                        max_length=50,
                        verbose_name="Forme",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DossierMedical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "groupe_sanguin",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                    ),
                ),
                ("allergies", models.TextField(blank=True, null=True)),
                ("maladies_chroniques", models.TextField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "couverture_medicale",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "etudiant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hopital.etudiant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnostic", models.TextField(blank=True, null=True)),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hopital.dossiermedical",
                    ),
                ),
                (
                    "medecin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hopital.medecin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duree", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hopital.consultation",
                    ),
                ),
                (
                    "medicament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="hopital.medicament",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RendezVous",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_rdv", models.DateField()),
                ("heure", models.TimeField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("prévu", "prévu"),
                            ("effectué", "effectué"),
                            ("raté", "raté"),
                        ],
                        default="prévu",
                        max_length=20,
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hopital.etudiant",
                    ),
                ),
                (
                    "medecin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hopital.medecin",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consultation",
            name="rdv",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT, to="hopital.rendezvous"
            ),
        ),
        migrations.CreateModel(
            name="Vaccination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_vaccin", models.CharField(max_length=100)),
                ("date_vaccin", models.DateTimeField(auto_now_add=True)),
                ("rappel", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hopital.dossiermedical",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="rendezvous",
            constraint=models.UniqueConstraint(
                fields=("medecin", "date_rdv", "heure"), name="unique_medecin_rdv"
            ),
        ),
        migrations.AddConstraint(
            model_name="rendezvous",
            constraint=models.UniqueConstraint(
                fields=("etudiant", "date_rdv", "heure"), name="unique_etudiant_rdv"
            ),
        ),
    ]
